# -*- coding: utf-8 -*-
"""CLASSIFICATION PREDICTIVE TASK.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19_PNTtyoGv6VJm7tX0l8jHOgV_AoktFK
"""

#Necseaary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import StratifiedKFold
from sklearn.base import clone
from sklearn.metrics import f1_score
from sklearn.model_selection import cross_val_score
from sklearn.pipeline import Pipeline
from sklearn.metrics import precision_score, recall_score
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score
from sklearn.metrics import precision_recall_curve
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import SGDClassifier
from sklearn.decomposition import PCA
import warnings
warnings.filterwarnings('ignore')


df = pd.read_csv("/content/plant_growth_data.csv")#Reading the data.

display(df.head())#Displaying the first five rows of the data.

df.keys()#Accesses the column names (keys) of a pandas DataFrame 'df'

df.describe()#Display statistical summary of the numerical variables of the data.

df.isnull().sum()#Checking for missing values

df.dtypes#Checking for datatypes

"""DATA PREPROCESSING"""

X = df.drop('Growth_Milestone', axis=1)#It removes the "Growth_Milestone" column from the dataframe and assign the rest to the a variable 'X'.
y = df['Growth_Milestone']#Assigns "Growth_Milestone" from the dataframe and assign it to a variable 'y'
categorical_cols = ['Soil_Type', 'Water_Frequency', 'Fertilizer_Type']#Defines categorical variables.
numerical_cols = ['Sunlight_Hours', 'Temperature', 'Humidity']#Define numerical variables.

preprocessor = ColumnTransformer(#It initializes and to apply specific preprocessing transformations to selected columns of a DataFrame.
    transformers=[#Defines a list of transformers for the ColumnTransformer, specifying preprocessing steps and target columns.
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_cols), # Added handle_unknown='ignore'
        ('num', Pipeline([('scaler', StandardScaler()), ('pca', PCA(n_components=1))]), numerical_cols) # Added PCA with n_components=2
    ])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)#Splits the feature data X and target y into training and testing sets with an 80-20 ratio, ensuring stratified sampling and reproducibility with a fixed random seed.

"""TRAIN A BINARY CLASSIFIER"""

sgd_clf = SGDClassifier(random_state=42)#Initializes an SGDClassifier from scikit-learn with a fixed random_state=42 for reproducible results, using stochastic gradient descent for classification.
X_train_processed = preprocessor.fit_transform(X_train)#Fits and transforms X_train using the preprocessor, applying defined column-specific preprocessing steps to produce X_train_processed.
sgd_clf.fit(X_train_processed, y_train)#Trains the SGDClassifier model sgd_clf on the preprocessed training data X_train_processed and corresponding target labels y_train using stochastic gradient descent.

skfolds = StratifiedKFold(n_splits=3, random_state=42, shuffle=True)#skfolds = StratifiedKFold(n_splits=3, random_state=42, shuffle=True)

for train_index, test_index in skfolds.split(X_train, y_train):#Iterates over train and test indices generated by StratifiedKFold for cross-validation on X_train and y_train
    clone_clf = clone(sgd_clf)#Creates a fresh copy of the SGDClassifier model to avoid modifying the original during cross-validation.
    X_train_folds = X_train.iloc[train_index]#Selects the training subset of X_train using the train_index for the current fold.
    y_train_folds = y_train.iloc[train_index]#Selects the corresponding training subset of y_train using the train_index for the current fold.
    X_test_fold = X_train.iloc[test_index]#Selects the test subset of X_train using the test_index for the current fold.
    y_test_fold = y_train.iloc[test_index]#Selects the corresponding test subset of y_train using the test_index for the current fold.

    # Apply preprocessing to the folds
    X_train_folds_processed = preprocessor.transform(X_train_folds)#Transforms the training subset of the current fold using the fitted preprocessor, producing processed features.
    X_test_fold_processed = preprocessor.transform(X_test_fold)#Transforms the test subset of the current fold using the fitted preprocessor, producing processed features.

    clone_clf.fit(X_train_folds_processed, y_train_folds)#Trains the cloned SGDClassifier model on the processed training data and corresponding labels for the current fold.
    y_pred = clone_clf.predict(X_test_fold_processed)#Generates predictions for the processed test data of the current fold using the trained cloned model.
    n_correct = sum(y_pred == y_test_fold)#Calculates the number of correct predictions by comparing predicted labels with actual test labels.
    print(n_correct / len(y_pred))#Prints the accuracy for the current fold by dividing the number of correct predictions by the total predictions.

# Create a pipeline that first preprocesses the data and then trains the classifier
pipeline = Pipeline([#Initializes a scikit-learn Pipeline object to sequentially apply preprocessing and classification steps.
    ('preprocessor', preprocessor),#Defines the first step named 'preprocessor', which applies the previously defined ColumnTransformer to process input data.
    ('classifier', sgd_clf)])#Defines the second step named 'classifier', which uses the previously initialized SGDClassifier for classification.

# Use the pipeline in cross_val_score
cross_val_score(pipeline, X_train, y_train, cv=3, scoring="accuracy")#Computes the pipeline's accuracy using 3-fold cross-validation on X_train and y_train, returning per-fold accuracy scores.

# Generate predictions on the training set
y_train_pred = sgd_clf.predict(X_train_processed)

# Calculate the confusion matrix
confusion_matrix(y_train, y_train_pred)

precision_score(y_train, y_train_pred)#Calculates the precision of the model on the training set

recall_score(y_train, y_train_pred)## Computes the recall of the model on the training set.

f1_score(y_train, y_train_pred)## Computes the F1 score of the model on the training set.

X_test_processed = preprocessor.transform(X_test)#Applies the preprocessing pipeline to the test data, transforming it into the same format as the training data for model prediction.
y_test_pred = sgd_clf.predict(X_test_processed)#Uses the trained SGD classifier to predict labels for the preprocessed test data, storing the predicted class labels in y_test_pred.
print("Test Precision:", precision_score(y_test, y_test_pred))#Compute the precision for the test data.
print("Test Recall:", recall_score(y_test, y_test_pred))#Evaluate the recall for the test data.
print("Test F1:", f1_score(y_test, y_test_pred))#Compute the F1-score for the test data.
print("Test Confusion Matrix:\n", confusion_matrix(y_test, y_test_pred))#Compute the confusion matrix for the test data.

sns.heatmap(confusion_matrix(y_test, y_test_pred), annot=True, cmap='summer', fmt='d')#Show a confusion matrix as heatmap
plt.xlabel('True Label')
plt.ylabel('Predicted Label')
plt.title('Confusion Matrix')
plt.show()

# Get the decision scores for the training data
y_scores = sgd_clf.decision_function(X_train_processed)#Computes the raw decision scores (distance from the decision boundary) for each training instance.Unlike predict(), this gives continuous values that can be thresholded for classification.

# Calculate precision-recall curve
precisions, recalls, thresholds = precision_recall_curve(y_train, y_scores)#Calculates precision and recall at different threshold values. Returns arrays of precision, recall, and the thresholds used to convert scores into class predictions.

def plot_precision_recall_vs_threshold(precisions, recalls, thresholds):#Defines a function to visualize how precision and recall change as the decision threshold changes.
  plt.plot(thresholds, precisions[:-1], "b--", label="Precision")
  plt.plot(thresholds, recalls[:-1], "g-", label="Recall")
  plt.xlabel("Threshold")
  plt.legend(loc="upper left")
  plt.ylim([0, 1])

plot_precision_recall_vs_threshold(precisions, recalls, thresholds)#Calls the plotting function to display the precision-recall vs. threshold curve.This helps to choose an optimal threshold that balances precision and recall based on your use case.
plt.show() #prints precision vs recall graph.

"""ROC CURVE"""

def plot_roc_curve(fpr, tpr, label=None):# Defines a function to plot the Receiver Operating Characteristic (ROC) curve.
  plt.plot(fpr, tpr, linewidth=2, label=label)
  plt.plot([0, 1], [0, 1], 'k--') # Dashed diagonal
  plt.xlabel('False Positive Rate')
  plt.ylabel('True Positive Rate (Recall)')
  plt.title('ROC Curve')
  plt.legend(loc="lower right")

# Calculate ROC curve
fpr, tpr, thresholds = roc_curve(y_train, y_scores)

# Plot ROC curve
plot_roc_curve(fpr, tpr)
plt.show()

roc_auc = roc_auc_score(y_train, y_scores)#Computes the Area Under the Receiver Operating Characteristic Curve (ROC AUC) for the training data.
print(f"{roc_auc:.3g}") #Print to 3significant figures.